### PR TITLE
Spanish support

### PR DESCRIPTION
**Pull request by paulomcnally**
In this pull request is working on the support of the Spanish language.

### CODE REVIEW

**Comment by carsonip** [comment]
Cool! I'll extract the English phrases in the script out to a file for translation later today.

**Comment by carsonip** [comment]
I've opened a new branch: `translation` for this PR. Please rebase your branch to work on it. Also please check `lambda/custom/language-strings.json` for the strings to be translated.

This is not tested yet, i.e. I have yet to upload and try this version with extracted strings, therefore it is not guaranteed to work at the moment. But let's finish the translation work first. Technical issues can be resolved quickly anyway.

If you are free, feel free to review my latest commit on the translation branch to make sure there are no careless mistakes. Thanks!

**Comment by paulomcnally** [comment]
I was working the same, but I see that you have already finished it. I'm going to work on the `lambda/custom/language-strings.jso` file as you mention.

**Comment by paulomcnally** [comment]
@carsonip done on https://github.com/carsonip/alexa-pomodoro/pull/11

**Comment by carsonip** [comment]
Nice. I'll test the skill in simulator soon.

**Comment by paulomcnally** [comment]
👉🏻👈🏻

**Comment by carsonip** [comment]
Got a bit busy at work, I'll do it ASAP.

**Pull request merged**
